// Stub: normally auto-generated by @storybook/react-native/metro/withStorybook
// when stories exist. P1-07 ships an empty story set; P1-08 will install the
// Metro plugin and codegen-overwrite this file.
import { view } from '@storybook/react-native';

export { view };
