// AUTO-GENERATED by scripts/storybook-generate.mjs — do not edit.
import { view } from '@storybook/react-native';
import '../src/design/icons/__stories__/Icon.stories.tsx';
import '../src/design/primitives/__stories__/Card.stories.tsx';
import '../src/design/primitives/__stories__/NumberStepper.stories.tsx';
import '../src/design/primitives/__stories__/PressButton.stories.tsx';
import '../src/design/primitives/__stories__/SegRail.stories.tsx';
import '../src/design/primitives/__stories__/WeightNum.stories.tsx';
export { view };
