#!/usr/bin/env bash
# Install local git hooks that run `pnpm verify` before each commit.
#
# Husky-free: no new npm dep, no node startup on every commit, no
# .husky/ directory. Just a shell script copied into .git/hooks/. Each
# contributor runs this once after cloning.
#
# Usage:
#   bash scripts/install-hooks.sh

set -euo pipefail

repo_root="$(git rev-parse --show-toplevel)"
hooks_dir="$repo_root/.git/hooks"

if [ ! -d "$hooks_dir" ]; then
  echo "✗ Couldn't find .git/hooks at $hooks_dir — are you in a git repo?" >&2
  exit 1
fi

hook_path="$hooks_dir/pre-commit"

cat > "$hook_path" <<'HOOK'
#!/usr/bin/env bash
# Auto-generated by scripts/install-hooks.sh — see that file for context.
#
# Runs the verify gauntlet before every commit so a broken bundle / red
# test never lands on a teammate's machine. Skip with `git commit -n`
# only when you know what you're doing.

set -euo pipefail

# Skip hook if the only files touched are docs / markdown — saves ~30s
# on doc-only commits.
staged=$(git diff --cached --name-only --diff-filter=ACMR | tr '\n' ' ')
if [ -z "${staged// /}" ]; then
  exit 0
fi
non_docs=$(echo "$staged" | tr ' ' '\n' | grep -vE '\.(md|txt)$' || true)
if [ -z "${non_docs// /}" ]; then
  echo "ℹ pre-commit: docs-only commit, skipping pnpm verify"
  exit 0
fi

echo "▶ pre-commit: pnpm verify (typecheck + lint + boundaries + test + bundle-check)"
pnpm verify
HOOK

chmod +x "$hook_path"

echo "✓ Installed pre-commit hook at $hook_path"
echo "  Bypass for a single commit with: git commit -n"
